services:
  - type: web
    name: archibald
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn mio_master.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: archibald-db
          property: connectionString

databases:
  - name: archibald-db
